/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as BecomeAHostRouteImport } from './routes/become-a-host'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as HSlugRouteImport } from './routes/h.$slug'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as HSlugIndexRouteImport } from './routes/h.$slug.index'
import { Route as HSlugSettingsRouteImport } from './routes/h.$slug.settings'
import { Route as HSlugReportsRouteImport } from './routes/h.$slug.reports'
import { Route as HSlugModerationRouteImport } from './routes/h.$slug.moderation'
import { Route as HSlugDashboardRouteImport } from './routes/h.$slug.dashboard'
import { Route as EventsIdEditRouteImport } from './routes/events.$id.edit'
import { Route as HSlugEventsNewRouteImport } from './routes/h.$slug.events.new'
import { Route as HSlugEventsIdCheckInRouteImport } from './routes/h.$slug.events.$id.check-in'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAHostRoute = BecomeAHostRouteImport.update({
  id: '/become-a-host',
  path: '/become-a-host',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HSlugRoute = HSlugRouteImport.update({
  id: '/h/$slug',
  path: '/h/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HSlugIndexRoute = HSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HSlugRoute,
} as any)
const HSlugSettingsRoute = HSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HSlugRoute,
} as any)
const HSlugReportsRoute = HSlugReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => HSlugRoute,
} as any)
const HSlugModerationRoute = HSlugModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => HSlugRoute,
} as any)
const HSlugDashboardRoute = HSlugDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HSlugRoute,
} as any)
const EventsIdEditRoute = EventsIdEditRouteImport.update({
  id: '/events/$id/edit',
  path: '/events/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const HSlugEventsNewRoute = HSlugEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => HSlugRoute,
} as any)
const HSlugEventsIdCheckInRoute = HSlugEventsIdCheckInRouteImport.update({
  id: '/events/$id/check-in',
  path: '/events/$id/check-in',
  getParentRoute: () => HSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/become-a-host': typeof BecomeAHostRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/tickets': typeof TicketsRoute
  '/e/$slug': typeof ESlugRoute
  '/h/$slug': typeof HSlugRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/events/$id/edit': typeof EventsIdEditRoute
  '/h/$slug/dashboard': typeof HSlugDashboardRoute
  '/h/$slug/moderation': typeof HSlugModerationRoute
  '/h/$slug/reports': typeof HSlugReportsRoute
  '/h/$slug/settings': typeof HSlugSettingsRoute
  '/h/$slug/': typeof HSlugIndexRoute
  '/h/$slug/events/new': typeof HSlugEventsNewRoute
  '/h/$slug/events/$id/check-in': typeof HSlugEventsIdCheckInRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become-a-host': typeof BecomeAHostRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/tickets': typeof TicketsRoute
  '/e/$slug': typeof ESlugRoute
  '/join/$token': typeof JoinTokenRoute
  '/events/$id/edit': typeof EventsIdEditRoute
  '/h/$slug/dashboard': typeof HSlugDashboardRoute
  '/h/$slug/moderation': typeof HSlugModerationRoute
  '/h/$slug/reports': typeof HSlugReportsRoute
  '/h/$slug/settings': typeof HSlugSettingsRoute
  '/h/$slug': typeof HSlugIndexRoute
  '/h/$slug/events/new': typeof HSlugEventsNewRoute
  '/h/$slug/events/$id/check-in': typeof HSlugEventsIdCheckInRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/become-a-host': typeof BecomeAHostRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/tickets': typeof TicketsRoute
  '/e/$slug': typeof ESlugRoute
  '/h/$slug': typeof HSlugRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/events/$id/edit': typeof EventsIdEditRoute
  '/h/$slug/dashboard': typeof HSlugDashboardRoute
  '/h/$slug/moderation': typeof HSlugModerationRoute
  '/h/$slug/reports': typeof HSlugReportsRoute
  '/h/$slug/settings': typeof HSlugSettingsRoute
  '/h/$slug/': typeof HSlugIndexRoute
  '/h/$slug/events/new': typeof HSlugEventsNewRoute
  '/h/$slug/events/$id/check-in': typeof HSlugEventsIdCheckInRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/become-a-host'
    | '/explore'
    | '/my-events'
    | '/onboarding'
    | '/sign-in'
    | '/tickets'
    | '/e/$slug'
    | '/h/$slug'
    | '/join/$token'
    | '/events/$id/edit'
    | '/h/$slug/dashboard'
    | '/h/$slug/moderation'
    | '/h/$slug/reports'
    | '/h/$slug/settings'
    | '/h/$slug/'
    | '/h/$slug/events/new'
    | '/h/$slug/events/$id/check-in'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become-a-host'
    | '/explore'
    | '/my-events'
    | '/onboarding'
    | '/sign-in'
    | '/tickets'
    | '/e/$slug'
    | '/join/$token'
    | '/events/$id/edit'
    | '/h/$slug/dashboard'
    | '/h/$slug/moderation'
    | '/h/$slug/reports'
    | '/h/$slug/settings'
    | '/h/$slug'
    | '/h/$slug/events/new'
    | '/h/$slug/events/$id/check-in'
  id:
    | '__root__'
    | '/'
    | '/become-a-host'
    | '/explore'
    | '/my-events'
    | '/onboarding'
    | '/sign-in'
    | '/tickets'
    | '/e/$slug'
    | '/h/$slug'
    | '/join/$token'
    | '/events/$id/edit'
    | '/h/$slug/dashboard'
    | '/h/$slug/moderation'
    | '/h/$slug/reports'
    | '/h/$slug/settings'
    | '/h/$slug/'
    | '/h/$slug/events/new'
    | '/h/$slug/events/$id/check-in'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BecomeAHostRoute: typeof BecomeAHostRoute
  ExploreRoute: typeof ExploreRoute
  MyEventsRoute: typeof MyEventsRoute
  OnboardingRoute: typeof OnboardingRoute
  SignInRoute: typeof SignInRoute
  TicketsRoute: typeof TicketsRoute
  ESlugRoute: typeof ESlugRoute
  HSlugRoute: typeof HSlugRouteWithChildren
  JoinTokenRoute: typeof JoinTokenRoute
  EventsIdEditRoute: typeof EventsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-host': {
      id: '/become-a-host'
      path: '/become-a-host'
      fullPath: '/become-a-host'
      preLoaderRoute: typeof BecomeAHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h/$slug': {
      id: '/h/$slug'
      path: '/h/$slug'
      fullPath: '/h/$slug'
      preLoaderRoute: typeof HSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h/$slug/': {
      id: '/h/$slug/'
      path: '/'
      fullPath: '/h/$slug/'
      preLoaderRoute: typeof HSlugIndexRouteImport
      parentRoute: typeof HSlugRoute
    }
    '/h/$slug/settings': {
      id: '/h/$slug/settings'
      path: '/settings'
      fullPath: '/h/$slug/settings'
      preLoaderRoute: typeof HSlugSettingsRouteImport
      parentRoute: typeof HSlugRoute
    }
    '/h/$slug/reports': {
      id: '/h/$slug/reports'
      path: '/reports'
      fullPath: '/h/$slug/reports'
      preLoaderRoute: typeof HSlugReportsRouteImport
      parentRoute: typeof HSlugRoute
    }
    '/h/$slug/moderation': {
      id: '/h/$slug/moderation'
      path: '/moderation'
      fullPath: '/h/$slug/moderation'
      preLoaderRoute: typeof HSlugModerationRouteImport
      parentRoute: typeof HSlugRoute
    }
    '/h/$slug/dashboard': {
      id: '/h/$slug/dashboard'
      path: '/dashboard'
      fullPath: '/h/$slug/dashboard'
      preLoaderRoute: typeof HSlugDashboardRouteImport
      parentRoute: typeof HSlugRoute
    }
    '/events/$id/edit': {
      id: '/events/$id/edit'
      path: '/events/$id/edit'
      fullPath: '/events/$id/edit'
      preLoaderRoute: typeof EventsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h/$slug/events/new': {
      id: '/h/$slug/events/new'
      path: '/events/new'
      fullPath: '/h/$slug/events/new'
      preLoaderRoute: typeof HSlugEventsNewRouteImport
      parentRoute: typeof HSlugRoute
    }
    '/h/$slug/events/$id/check-in': {
      id: '/h/$slug/events/$id/check-in'
      path: '/events/$id/check-in'
      fullPath: '/h/$slug/events/$id/check-in'
      preLoaderRoute: typeof HSlugEventsIdCheckInRouteImport
      parentRoute: typeof HSlugRoute
    }
  }
}

interface HSlugRouteChildren {
  HSlugDashboardRoute: typeof HSlugDashboardRoute
  HSlugModerationRoute: typeof HSlugModerationRoute
  HSlugReportsRoute: typeof HSlugReportsRoute
  HSlugSettingsRoute: typeof HSlugSettingsRoute
  HSlugIndexRoute: typeof HSlugIndexRoute
  HSlugEventsNewRoute: typeof HSlugEventsNewRoute
  HSlugEventsIdCheckInRoute: typeof HSlugEventsIdCheckInRoute
}

const HSlugRouteChildren: HSlugRouteChildren = {
  HSlugDashboardRoute: HSlugDashboardRoute,
  HSlugModerationRoute: HSlugModerationRoute,
  HSlugReportsRoute: HSlugReportsRoute,
  HSlugSettingsRoute: HSlugSettingsRoute,
  HSlugIndexRoute: HSlugIndexRoute,
  HSlugEventsNewRoute: HSlugEventsNewRoute,
  HSlugEventsIdCheckInRoute: HSlugEventsIdCheckInRoute,
}

const HSlugRouteWithChildren = HSlugRoute._addFileChildren(HSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BecomeAHostRoute: BecomeAHostRoute,
  ExploreRoute: ExploreRoute,
  MyEventsRoute: MyEventsRoute,
  OnboardingRoute: OnboardingRoute,
  SignInRoute: SignInRoute,
  TicketsRoute: TicketsRoute,
  ESlugRoute: ESlugRoute,
  HSlugRoute: HSlugRouteWithChildren,
  JoinTokenRoute: JoinTokenRoute,
  EventsIdEditRoute: EventsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
